### ISSUE TITLE
Error can help fixed

### ISSUE THREAD

**Issue by lolminerxmrig** [montysecurity/InfraSpyder#1]
Hi.

InfraSpyder# python3 infraspider.py -s "services.http.response.html_title='WSO2 Management Console'" -p WSO2.txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/shodan/client.py", line 550, in search_cursor
    results = self.search(query, minify=minify, page=page, fields=fields)
  File "/usr/local/lib/python3.10/dist-packages/shodan/client.py", line 520, in search
    return self._request('/shodan/host/search', args)
  File "/usr/local/lib/python3.10/dist-packages/shodan/client.py", line 336, in _request
    raise APIError(error)
shodan.exception.APIError: Invalid API key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/work/InfraSpyder/infraspider.py", line 35, in <module>
    for result in shodan_api.search_cursor(shodan_query):
  File "/usr/local/lib/python3.10/dist-packages/shodan/client.py", line 561, in search_cursor
    raise APIError('Retry limit reached ({:d})'.format(retries))
shodan.exception.APIError: Retry limit reached (5)

**Comment by montysecurity** [comment]
The script uses variables to pull the API keys - CENSYS_API_ID, CENSYS_API_SECRET, SHODAN_API_KEY
